CUSTOM_DIR="$1"
PACKAGE_NAME="$2"

echo "FILES DIR : $CUSTOM_DIR"

export ANDROID_PACKAGE_NAME=$PACKAGE_NAME

export PATH=$CUSTOM_DIR/usr/bin:$CUSTOM_DIR/bin:$PATH

export LD_LIBRARY_PATH="$LD_LIBRARY_PATH$CUSTOM_DIR/usr/lib"

export HOME="$CUSTOM_DIR"